# Generated by Django 5.2.6 on 2025-09-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_movie_actors_alter_movie_genres_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_user_created_at',
        ),
    ]
